name: build
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: pnpm/action-setup@v4
     with: { version: 9 }
   - uses: actions/setup-node@v4
     with: { node-version: 20 }
   - uses: actions/setup-java@v4
     with: { distribution: 'temurin', java-version: '17' }
   - uses: android-actions/setup-android@v3
   - run: echo "shamefully-hoist=true" >.npmrc
   - run: rm -rf node_modules
   - run: pnpm add expo@57.0.19 --no-frozen-lockfile
   - run: pnpm install --no-frozen-lockfile
   - run: npx expo prebuild --platform android --clean --no-install
   - run: cd android && chmod +x gradlew &&./gradlew assembleDebug
   - uses: actions/upload-artifact@v4
     with: { name: apk, path: android/app/build/outputs/apk/debug/app-debug.apk }
